version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/
    overwrite: yes

permissions:
  - object: /home/ubuntu/app/deploy.sh
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: "755" # 또는 "rwxr-xr-x" (Octal 또는 문자열 모두 사용 가능)

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ubuntu
